services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: svechka
      POSTGRES_USER: svechka
      POSTGRES_PASSWORD: svechka
    ports:
      - "5432:5432"
    volumes:
      - svechka-backend-postgres-data:/var/lib/postgresql/data

volumes:
  svechka-backend-postgres-data:
